### ISSUE TITLE
shape problem 

### ISSUE THREAD

**Issue by Fakhraddin** [rolczynski/Automatic-Speech-Recognition#17]
I have an error when I run the basic,py  'ValueError: Error when checking input: expected X to have 3 dimensions, but got array with shape (41440, 1)' error.

**Comment by rolczynski** [comment]
Hey, sorry for the late response. Have you resolved this problem?

**Comment by Fakhraddin** [comment]
Hi ,I haven't yet.

**Comment by Drazcat** [comment]
same issue here, the weird part is that every time i try to train, the shape duplicates its value. i started  with a shape(20720, 1), and ended with an input shape in the millions. Its a very weird bug and first time i see it

**Comment by rolczynski** [comment]
Solved - I had to change the `wrap preprocess` in the pipeline.
