### ISSUE TITLE
missing optimizer class

### ISSUE THREAD

**Issue by Drazcat** [rolczynski/Automatic-Speech-Recognition#18]
when i try to train, i cant because the optimizer class doesnt exists 

--------------------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "C:\Users\benja\OneDrive\Desktop\Drazcat\python\Automatic-Speech-Recognition\train.py", line 19, in <module>
    optimizer = asr.optimizer.Adam(
AttributeError: module 'automatic_speech_recognition' has no attribute 'optimizer'

**Comment by rolczynski** [comment]
Please `import tensorflow as tf` and then use `tf.optimizer` ;)
