### ISSUE TITLE
Pretrained model available?

### ISSUE THREAD

**Issue by DevZiegler** [rolczynski/Automatic-Speech-Recognition#4]
Hi, first of all, thanks for the work and the project.
Are there any pretrained models for your implementation?
And if so, where can I find them?
thx

**Comment by rolczynski** [comment]
Hey!
Thank you. Unfortunately, the experiments still are in progress. 
I hope it will change soon.
Rafal

**Comment by AleksandraPestka** [comment]
Hello, 
Thanks a lot for a great piece of code.
I guess that there hasn't been pretrained model yet and I have to train it by myself?

**Comment by rolczynski** [comment]
hey ! Thank you, unfortunately still no... we work on

**Comment by AleksandraPestka** [comment]
@rolczynski  Do you recommend any Polish (or even English) free dataset to train your model? (which doesn't require a lot of modification e.g. wave files up to 5 sec)

**Comment by rolczynski** [comment]
@AleksandraPestka I highly recommend https://github.com/danijel3/ClarinStudioKaldi, and you can contact with @danijel3. We will publish here the initial version of the Polish model at the beginning of September

**Comment by tomekkorbak** [comment]
@AleksandraPestka, we've just hosted an initial pre-trained model, see instructions here:
https://github.com/rolczynski/DeepSpeech-Keras/tree/master/models

**Comment by AleksandraPestka** [comment]
Could you guide me how to test this model with pre-trained weights and .wav files provided in test/data/audio ? I've tried to follow the code in readme, but I've got stuck with the folders hierarchy. To be precise - which script should I run to test this model and from which folder? ( in order to avoid errors)

**Comment by rolczynski** [comment]
@AleksandraPestka, we can arrange the 1hour session and together we will explore how it works, but... one thing! Then you write README, right?

**Comment by AleksandraPestka** [comment]
Are you asking me about updating README? As a nonauthor of this project I think I'm not supposed to do that...  but if I can still help with anything, I will

**Comment by AleksandraPestka** [comment]
Is it still possible to get help to test pre-trained model?
