### ISSUE TITLE
Conda packages are unavailable in windows 10.

### ISSUE THREAD

**Issue by chmodsss** [rolczynski/Automatic-Speech-Recognition#9]
1. Some of the mentioned conda packages are available in pip but not in conda.
2. Apart from that, conda is unable to identify the packages due to the mentioning of build strings in environment yml file.

**Comment by rolczynski** [comment]
hey @chmodsss, thank you for the issue. I have to fix it

**Comment by chmodsss** [comment]
Do you mind if I send a pull request. I kind of sorted it out. For future, use `conda env export --no-builds > env.yml` when writing environment yml files. It neglects the build strings.

**Comment by rolczynski** [comment]
Excellent, please send the PR
